        <div id="footer">
            <div class="container_12">
                <div class="grid_2">
                    <h4>Shows</h4>
                    <ul>
                        <li>
                            <a href="/talkshow" title="The Talk Show">The Talk Show</a>
                        </li>
                        <li>
                            <a href="/b2w" title="Back to Work with Merlin Mann">Back to Work</a>
                        </li>
                        <li>
                            <a href="/criticalpath" title="The Critical Path">The Critical Path</a>
                        </li>
                        <li>
                            <a href="/buildanalyze" title="The Pipeline">Build &amp; Analyze</a>
                        </li>
                        <li>
                            <a href="/hypercritical" title="Hypercritical with John Siracusa">Hypercritical</a>
                        </li>
                        <li>
                            <a href="/broadcasts" title="More Broadcasts">More →</a>
                        </li>
                    </ul>
                </div>
                <div class="grid_2">
                    <h4>Shows</h4>
                    <ul>
                        <li>
                            <a href="/talkshow" title="The Talk Show">The Talk Show</a>
                        </li>
                        <li>
                            <a href="/b2w" title="Back to Work with Merlin Mann">Back to Work</a>
                        </li>
                        <li>
                            <a href="/criticalpath" title="The Critical Path">The Critical Path</a>
                        </li>
                        <li>
                            <a href="/buildanalyze" title="The Pipeline">Build &amp; Analyze</a>
                        </li>
                        <li>
                            <a href="/hypercritical" title="Hypercritical with John Siracusa">Hypercritical</a>
                        </li>
                        <li>
                            <a href="/broadcasts" title="More Broadcasts">More →</a>
                        </li>
                    </ul>
                </div>
                <div class="grid_2">
                    <h4>Shows</h4>
                    <ul>
                        <li>
                            <a href="/talkshow" title="The Talk Show">The Talk Show</a>
                        </li>
                        <li>
                            <a href="/b2w" title="Back to Work with Merlin Mann">Back to Work</a>
                        </li>
                        <li>
                            <a href="/criticalpath" title="The Critical Path">The Critical Path</a>
                        </li>
                        <li>
                            <a href="/buildanalyze" title="The Pipeline">Build &amp; Analyze</a>
                        </li>
                        <li>
                            <a href="/hypercritical" title="Hypercritical with John Siracusa">Hypercritical</a>
                        </li>
                        <li>
                            <a href="/broadcasts" title="More Broadcasts">More →</a>
                        </li>
                    </ul>
                </div>
                <div class="grid_2">
                    <h4>Shows</h4>
                    <ul>
                        <li>
                            <a href="/talkshow" title="The Talk Show">The Talk Show</a>
                        </li>
                        <li>
                            <a href="/b2w" title="Back to Work with Merlin Mann">Back to Work</a>
                        </li>
                        <li>
                            <a href="/criticalpath" title="The Critical Path">The Critical Path</a>
                        </li>
                        <li>
                            <a href="/buildanalyze" title="The Pipeline">Build &amp; Analyze</a>
                        </li>
                        <li>
                            <a href="/hypercritical" title="Hypercritical with John Siracusa">Hypercritical</a>
                        </li>
                        <li>
                            <a href="/broadcasts" title="More Broadcasts">More →</a>
                        </li>
                    </ul>
                </div>
                <div class="clear"></div>
                <div class="grid_12">
                    <p>
                        Copyright © 2009–2012 by 5by5 Corporation. All Rights Reserved · Hosted by <a href="http://joyent.com">Joyent</a> · Video hosting by <a href="http://wistia.com/5by5" title="Video hosting and analytics by Wistia">Wistia</a> · Fonts by <a href="http://typekit.com">Typekit</a> · Coded by <a href="http://danbenjamin.com" title="Your Internet Pal Dan Benjamin">Your Internet Pal</a>
                    </p>
                </div>
                <div class="clear"></div>
            </div>
        </div>