<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>    
<link rel="stylesheet" href="../../Styles/css/reset.css" />
<link rel="stylesheet" href="../../Styles/css/text.css" />
<link rel="stylesheet" href="../../Styles/css/960.css" />
<link rel="stylesheet" href="../../Styles/css/screen.css" />
<link rel="stylesheet" href="../../Styles/css/style.css" />
<link rel="stylesheet" href="../../Styles/css/demo.css" />
<link rel="stylesheet" type="text/css" href="../../Styles/style.css" />

<script type="text/javascript" src="../../Scripts/modernizr.custom.53451.js"></script>
<script type="text/javascript" src="../../Scripts/jquery-1.7.1.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="http://connect.facebook.net/en_US/all.js"></script>
<script type="text/javascript" src="../../Scripts/jquery.form.js"></script>
<script type="text/javascript" src="../../Scripts/jquery-ui.min.js "></script>
<script type="text/javascript" src="../../Scripts/utils.js "></script>